resources:
- aws-lb-controller-bundle.yaml
- aws-resolver-rules-operator.yaml
- aws-vpc-operator.yaml
- capa-iam-operator.yaml
- cluster-api-events.yaml
- cluster-api-provider-aws.yaml
- cluster-api.yaml
- dashboards.yaml
- deletion-blocker-operator.yaml
- dex-app.yaml
- dex-operator.yaml
- encryption-provider-operator.yaml
- etcd-backup-operator.yaml
- event-exporter-app.yaml
- falco.yaml
- fluent-logshipping-app.yaml
- gateway-api-bundle.yaml
- grafana.yaml
- ingress-nginx.yaml
- keda.yaml
- konfiguration.v2.yaml
- kube-downscaler.yaml
- kyverno-policies-connectivity.yaml
- kyverno-policies-dx.yaml
- kyverno-policies-observability.yaml
- kyverno-policies-ux.yaml
- loki.yaml
- mimir.yaml
- oauth2-proxy.yaml
- object-storage-operator.yaml
- observability-operator.yaml
- observability-platform-api.yaml
- organization-operator.yaml
- plugin-barman-cloud.yaml
- prometheus-remotewrite.yaml
- rbac-operator.yaml
- silence-operator.yaml
- sloth-rules.yaml
- sloth.yaml
- starboard-exporter.yaml
- teleport-operator.yaml
- teleport-tbot.yaml
- tempo.yaml
- trivy-operator.yaml
- trivy.yaml
