resources:
- aws-lb-controller-bundle.yaml
- aws-resolver-rules-operator.yaml
- aws-vpc-operator.yaml
- capa-iam-operator.yaml
- cluster-api-provider-aws.yaml
- dashboards.yaml
- deletion-blocker-operator.yaml
- dex-app.yaml
- dex-operator.yaml
- etcd-backup-operator.yaml
- event-exporter-app.yaml
- falco.yaml
- fluent-logshipping-app.yaml
- gateway-api-bundle.yaml
- keda.yaml
- konfiguration.v2.yaml
- loki.yaml
- mimir.yaml
- oauth2-proxy.yaml
- rbac-operator.yaml
- silence-operator.yaml
- starboard-exporter.yaml
- teleport-operator.yaml
- teleport-tbot.yaml
- tempo.yaml
- trivy-operator.yaml
- trivy.yaml
