resources:
- aws-lb-controller-bundle.yaml
- aws-resolver-rules-operator.yaml
- aws-vpc-operator.yaml
- capa-iam-operator.yaml
- cluster-api-provider-aws.yaml
- dex-app.yaml
- dex-operator.yaml
- event-exporter-app.yaml
- konfiguration.v2.yaml
- teleport-operator.yaml
- teleport-tbot.yaml
- tempo.yaml
- trivy-operator.yaml
- trivy.yaml
