---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: ingress-nginx
  namespace: giantswarm
spec:
  interval: 10m
  provider: generic
  ref:
    semver: x.x.x
  url: oci://gsoci.azurecr.io/charts/giantswarm/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: giantswarm
  annotations:
    app-operator.giantswarm.io/paused: 'true'
spec:
  chartRef:
    kind: OCIRepository
    name: ingress-nginx
    namespace: giantswarm
  install:
    remediation:
      remediateLastFailure: false
      retries: 10
  interval: 5m
  releaseName: ingress-nginx
  targetNamespace: giantswarm
  timeout: 10m
  upgrade:
    remediation:
      remediateLastFailure: false
      retries: 10
  valuesFrom:
  - kind: ConfigMap
    name: ingress-nginx-konfiguration
    valuesKey: configmap-values.yaml
  - kind: Secret
    name: ingress-nginx-konfiguration
    valuesKey: secret-values.yaml
